apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
    app: msa-banking-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: account-service
      app: msa-banking-app

  template:
    metadata:
      name: account-msa-pod
      labels:
        name: account-service
        app: msa-banking-app
    spec:
      containers:
      - name: account-container
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 600m
            memory: 600Mi

      imagePullSecrets:
          - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
  labels:
    name: account-service
    app: msa-banking-app

spec:
  type: ClusterIP
  ports:
  -  protocol: TCP
     targetPort: 3333
     port: 3333

  selector:
    name: account-service
    app: msa-banking-app